### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by Zenahr** [Energy0124/UnrealEngineAssetManager#3]
Would be cool to have 1-2 screenshots and maybe at least not have the boilerplate readme sitting there.
By the name of it it sounds like a cool project though.

**Comment by Energy0124** [comment]
Thank you for your interest! At the moment it's basically a searching tool for filtering and sorting the marketplace asset vault, as the official launcher's asset vault searching is insufficient and laggy when there are too many assets. I have over 800 assets in my vault and it is extremely difficult to find the asset I needed.

I have yet to write a readme as it's not yet ready for release. It's mostly functional, but it still needs some polishment. I will try to wrap it up and release the first version this week.

**Comment by Energy0124** [comment]
Readme and screenshots are added.
